### PR TITLE
Major update and refactor

### PR DESCRIPTION
**Pull request by joshdavham**
This PR is both a major update and a refactoring

Firstly, this PR closes the following issues:

#56 -> Py-FSRS now has re/learning steps that can be disabled.
#60 -> The scheduler now fuzzes intervals by default, but can also be disabled
#63 -> Custom re/learning steps can now be configured to keep cards in the Learning and Relearning states longer, if desired

This PR also makes the following major changes:
- This package now requires python 3.10+. This is so that modern type annotation can be used in favor of old type annotation
```python
# modern
x: int | None = 2

# old
from typing import Optional
x: Optional[int] = 2
```
- The `FSRS` class has been renamed to `Scheduler`
- The `SchedulingInfo`, `SchedulingCards` and `Parameters` have been removed.
- The `Scheduler.repeat()` method has been replaced by the `Scheduler.review_card()` method.
- `Scheduler.request_retention` has been renamed to `Scheduler.desired_retention` to fit more closely with Anki.
- The `Scheduler` now has `learning_steps` and `relearning_steps` that can be set by the user.
- `State.New` has been removed. New cards now start off in the `State.Learning` state (which is still equal to 1).
- The scheduler can now do fuzzing. It is enabled by default and can be disabled with `Scheduler(enable_fuzzing=False)`
- Cards reviewed more than once in the same day now use the short-term stability formula, regardless of their state.
- The `now` parameters when reviewing cards has been renamed to `review_datetime` to be more explicit.
- The following attributes have been removed from the Card class as they don't affect scheduling: `Card.elapsed_days`, `Card.scheduled_days`, `Card.reps`, `Card.lapses`.
- The `Card` class now has a `Card.id` attribute. This is so that the the same card can be identified across review logs. By default, if unspecified, it will be set to the epoch miliseconds of when the card was created, similar to Anki.
- `ReviewLog` objects now have a `ReviewLog.card` variable which is a copy of the card that was reviewed. In addition, there's also the optional `ReviewLog.review_duration` which is the number of miliseconds it took to review the card, similar to Anki review logs.
- I bumped the major version `3.1.0` -> `4.0.0`
- I also removed the ALGORITHM.md and fsrs-diagram.png files from the repo as they are now outdated. I'm hoping to perhaps create more documentation to replace these files in the future to clearly explain how the scheduler works.
- And of course, I also updated the README.

As for changes relevant to us maintainers:
- I removed `models.py` in favor of a single `fsrs.py` file for simplicity.
- I also added 12 more unit tests.
  - With very minor changes, all the previous tests still pass!

Overall, I'm hoping that this update will make the package feel more modern, easy to use and understand as well as make it easier to maintain.

Let me know if you have any questions 👍

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
> * I removed `models.py` in favor of a single `fsrs.py` file for simplicity.

It makes the code review very inconvenient. Git just tells me that a lot of codes are removed and added...

**Review by L-M-Sherlock — APPROVED** [review]
LGTM (I didn't see the code. The unit tests are passed, so it's OK.)

**Comment by joshdavham** [comment]
> It makes the code review very inconvenient. Git just tells me that a lot of codes are removed and added...

Good point. I guess in retrospect, it would've been better to save moving models.py into fsrs.py for a future commit in order to make these code changes easier to review.

> LGTM (I didn't see the code. The unit tests are passed, so it's OK.)

Sounds good!

**Comment by Brentably** [comment]
How to migrate if you're using 3.1.0?

**Comment by joshdavham** [comment]
@Brentably I saw your message before you deleted it and just added some release notes if you're still having trouble with the upgrade. You can find the notes here [here](https://github.com/open-spaced-repetition/py-fsrs/releases/tag/v4.0.0).

**Pull request merged**
