### PR TITLE
fix timezone error

### PR DESCRIPTION
**Pull request by T2XX**
通过更换时区表达修复错误 can not import UTC
Fix error can not import UTC by using timezone.utc

UTC 类已经遗弃

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Which version of Python do you use when you run the test?

**Comment by T2XX** [comment]
I run the test in 3.9.19, conda env
```python
line 2, in <module>
    from datetime import datetime, UTC
ImportError: cannot import name 'UTC' from 'datetime' 
```

**Comment by T2XX** [comment]
I also test it in 3.11.5 ,it work properly.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM. Thanks for your contribution!

**Pull request merged**
